#!/bin/bash

sudo apt-get update
sudo apt-get install nginx

curl -i -X POST -H 'Content-Type: application/json' -d '{"jackPot": "winwin"}' http://127.0.0.1/abracadabra



docker network create web_network \
--driver overlay \
--subnet=192.168.100.0/24

docker volume create web_static

docker service create \
--name webapp \
--mount src=web_static,dst=/app/static \
--network web_network \
fb/backend


docker service create \
--name webproxy \
--network web_network \
--mount src=web_static,dst=/var/www-data \
--mount type=bind,src=/Users/alexey/fb_test/alexey-task/front/ngingx_conf_d,dst=/etc/nginx/conf.d \
-p 80:80 \
nginx


docker run -d -p 8081:80 front
docker network connect --ip 192.168.1.3 internal_network cc8cdf28de3b66d378889665c6a877d358eb70f9f9095155fe7ce4ac4a7c2268